### ISSUE TITLE
iOS 9.0: 'UIPopoverController' is deprecated

### ISSUE THREAD

**Issue by deanezra** [Busta117/SBPickerSelector#12]
If you target IOS9 or later, Xcode tells you that the UIPopoverController is deprecated:

Popovers are now implemented as UIViewController presentations. Use a modal presentation style of UIModalPresentationPopover and UIPopoverPresentationController.

The UIPopoverController use is in the SBPickerSelector.h header:

UIPopoverController *popOver_;

**Comment by Busta117** [comment]
fixed, check the latest version already in cocoapods
