### ISSUE TITLE
SBPickerSelectorDateTypeOnlyMonthAndYear does not select the provided date!

### ISSUE THREAD

**Issue by MKGitHub** [Busta117/SBPickerSelector#15]
![2016-10-14 at 15 21 23](https://cloud.githubusercontent.com/assets/535550/19389009/81a6e5dc-9222-11e6-8dae-e90a0ad8940a.png)

Selects the current month & year! It should be the provided one!

<img width="455" alt="2016-10-14 at 15 21 13" src="https://cloud.githubusercontent.com/assets/535550/19389020/90c4d9de-9222-11e6-95f2-1d541c147603.png">

**Comment by Busta117** [comment]
fixed, you can check it in the version 1.2.0 already on cocoapods
to set a default date you have to use the `defaultDate ` on SBPickerSelector
in your code:

```objective-c 
picker.defaultDate = [NSDate dateWithTimeIntervalSinceNow:(60 * 60 * 24 * 100)];
```
