### ISSUE TITLE
Dismiss once click done 

### ISSUE THREAD

**Issue by tbalancin** [Busta117/SBPickerSelector#22]
Hello @Busta117 thank you very much for your framework, I had implemented with success but I have a question..

I'm using the last version and doing the doneButton on the following way:

```
pickerFramework.doneButtonTitle = "Done"
        pickerFramework.doneButton?.tintColor = UIColor.white
        pickerFramework.doneButton?.target = self
        pickerFramework.doneButton?.action = #selector(closePickerChoice)
```
But it don't dismiss the picker anymore, which function should I use to dismiss the picker?

I have this on my closePickerChoice()

```
func closePickerChoice() {
        
       pickerFramework.dismiss(animated: false) { 
            return true
        }
}
```
Best regards.

**Comment by Busta117** [comment]
hi tbalancin, thanks for using SBPickerSelector

as you can see, there is a delegate to implement, you need to implement it and its depends on which picker are you using (date picker or text picker), the done button call the following methods, but remember add the `pickerFramework.delegate = self` , picker will dismiss automatically

```swift
func pickerSelector(_ selector: SBPickerSelector, dateSelected date: Date) {
    // code here to get the date selected
}
    
func pickerSelector(_ selector: SBPickerSelector, selectedValues values: [String], atIndexes idxs: [NSNumber]){
  // code here to get the text
}
```
