### ISSUE TITLE
Cann't show Picker with some custom index already selected

### ISSUE THREAD

**Issue by RajChanchal** [Busta117/SBPickerSelector#7]
HI Busta117, thanks for the control. I have selected an item for example and press the Done button. Then, if I open press the picker button that shows the picker, it doesn't show the value selected!

**Comment by Busta117** [comment]
hi Raj
that isn't an issue, when you display the picker is a new instance of the piker, if you want the piker shows the current element selected you can do it by setting the default index before display the picker

**Comment by RajChanchal** [comment]
But there is nothing like defaultIndex property. It is defaultDate while I am using the picker for picking up a single string from the array of strings.

**Comment by Busta117** [comment]
yeah, you are right, the solution is this method:

var newPickerIdx = 2 //this is your default index
SBPicker.pickerView.selectRow(newPickerIdx,inComponent:0, animated:false)
