### ISSUE TITLE
Setting maximum year

### ISSUE THREAD

**Issue by MarijaGvozdenovic** [Busta117/SBPickerSelector#8]
I'm having issues setting the maximum year for date pickers, I've tried setting maximum date and maximum/minimum year but nothing worked.

**Comment by Busta117** [comment]
Hi, 

Try with 

YourSBPicker.datePicker.maximum 

You need get the datePiker in the sbPicker


Santiago Bustamante
Ingeniero de Sistemas
Universidad EAFIT
Medellín - Colombia
